/// Flutter icons CustomKeyIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.

import 'package:flutter/widgets.dart';

/// A collection of custom key icons.
class CustomKeyIcons {
  CustomKeyIcons._();

  static const _kFontFam = 'CustomKeyIcons';
  static const String? _kFontPkg = 'math_keyboard';

  /// Key icon used for indicating multiple symbols.
  static const IconData key_symbols =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
