/// Label for the Pub link button.
const pubLabel = 'Pub';

/// Pub URL of the math_keyboard package.
const pubUrl = 'https://pub.dev/packages/math_keyboard';

/// Pub shields badge for math_keyboard.
const pubBadgeUrl = 'https://img.shields.io/pub/v/math_keyboard';

/// Label for the GitHub link button.
const gitHubLabel = 'GitHub';

/// URL of the GitHub repo.
const gitHubUrl = 'https://github.com/simpleclub/math_keyboard';

/// GitHub icon for light mode.
const lightGitHubIconUrl = 'https://i.imgur.com/B9jYEyK.png';

/// GitHub icon for dark mode.
const darkGitHubIconUrl = 'https://i.imgur.com/dxmmhk4.png';

/// Label for the documentation link button.
const docsLabel = 'API reference';

/// URL of the API reference generated by Pub.
const docsUrl = 'https://pub.dev/documentation/math_keyboard/latest';

/// Title for the demo app.
const appTitle =
    'math_keyboard - Fully integrated math expression editing in Flutter';

/// The header of the demo app.
const header = 'math_keyboard';

/// Highlighted prefix for the project description.
const descriptionPrefix = 'Fully integrated';

/// Description of the math_keyboard project.
const description = 'math expression editing in Flutter.';

/// Tooltip for the brightness switch to toggle between light and dark mode.
const brightnessSwitchTooltip = 'Toggle brightness';

/// The simpleclub logo for dark mode.
const darkLogoUrl = 'https://i.imgur.com/yhLSa1c.png';

/// The simpleclub logo for light mode.
const lightLogoUrl = 'https://i.imgur.com/kgr9HW5.png';

/// Name used as a tooltip label.
const organizationName = 'simpleclub';

/// URL for simpleclub's GitHub.
const organizationUrl = 'https://github.com/simpleclub';
