name: publish

on:
  push:
    branches:
      - main

jobs:
  pana:
    timeout-minutes: 9
    runs-on: ubuntu-latest
    name: ${{ matrix.package }} configuration
    strategy:
      matrix:
        package:
          - 'math_keyboard'
      fail-fast: false

    steps:
      - uses: actions/checkout@v2.3.3
      - uses: axel-op/dart-package-analyzer@v3
        with:
          relativePath: ${{ matrix.package }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}

  publish:
    needs: pana
    timeout-minutes: 4
    runs-on: ubuntu-latest
    name: ${{ matrix.package }} publishing
    permissions:
      id-token: write # Allows to publish to pub.dev without personal credentials
    strategy:
      matrix:
        package:
          - 'math_keyboard'
      fail-fast: false

    steps:
      - uses: actions/checkout@v2.3.3
        with:
          fetch-depth: 2

      - name: Check package Pubspec
        id: pubspec
        run: |
          set +e
          git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep '${{ matrix.package }}/pubspec.yaml' &> /dev/null
          echo ::set-output name=changed::$?
          set -e
      - name: Extract package version
        if: steps.pubspec.outputs.changed == 0
        run: |
          cd ${{ matrix.package }}
          echo "VERSION=$(awk '{if ($1 ~ /^version:/) print $2}' pubspec.yaml)" >> $GITHUB_ENV
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Get pub.dev token
        run: |
          PUB_TOKEN=$(curl --retry 5 --retry-connrefused -sLS "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=https://pub.dev" -H "User-Agent: actions/oidc-client" -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" | jq -r '.value')
          echo "PUB_TOKEN=${PUB_TOKEN}" >> $GITHUB_ENV
          export PUB_TOKEN
          flutter pub token add https://pub.dev --env-var PUB_TOKEN
      - name: Install dependencies
        run: flutter pub get
        working-directory: ${{ matrix.package }}
      - name: publish to pub.dev
        if: steps.pubspec.outputs.changed == 0
        run: flutter pub publish --force
        working-directory: ${{ matrix.package }}
      - name: Create release
        if: steps.pubspec.outputs.changed == 0
        id: create_release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ matrix.package }}-v${{ env.VERSION }}
          release_name: ${{ matrix.package }} v${{ env.VERSION }}
          draft: false
          prerelease: false